name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.org'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - 29.1
          - release-snapshot
          - snapshot
        include:
          - os: macos-latest
            emacs_version: 29.1
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: test
        run: |
          export HOME="/home/runner/work/.emacs.d"; \
          mkdir -p $HOME/.emacs.d/elpa/gnupg && gpg --homedir $HOME/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40; \
          emacs -q --batch \
          --eval "(message \"Testing...\")" \
          --eval "(let ((early-init-file (locate-user-emacs-file \"early-init.el\"))
                        (user-init-file (locate-user-emacs-file \"init.el\")))
                    (and (>= emacs-major-version 27) (load early-init-file))
                    (load user-init-file))" \
          --eval "(message \"Testing...done\")"
